### ISSUE TITLE
Get rid of TODO, revert bootstrap URL, get all depends into setup.sh

### ISSUE THREAD

**Issue by dragon788** [dragon788/vmware-tools-patches#1]
The other stuff looks decent, but I'd like to get this done before I pull request to Rasa's awesome repo.

**Comment by rasa** [comment]
I like your work, and will accept the PR when it's ready.

**Comment by dragon788** [comment]
@rasa I've made these changes and opened a pull request, let me know if you see anything else that needs tweaked.
