### ISSUE TITLE
Arch problem: execution aborted

### ISSUE THREAD

**Issue by snazzybunny** [dragon788/vmware-tools-patches#2]
I read your post on raka's vmware-tools-patches repo and then copied this repo and did the same commands. Any idea why I am getting this problem on Archlinux? 

Here is the pastebin: http://pastebin.com/wa6Rk3en

**Comment by dragon788** [comment]
It appears that you already have VMware tools installed. I believe there is a force option to the install that may allow it to remove that existing install automatically, but that came in after VMware tools 9.6.x, so I'd suggest getting the latest (Fusion 8.1.0).

**Comment by dragon788** [comment]
@andyph666 This should be fixed by https://github.com/dragon788/vmware-tools-patches/pull/3 as the actual cause of the failure was the rc0.d - rc6.d directories not existing, and VMware tools is currently hardcoded to look for those. I've opened a pull request to the rasa repo for that fix as well.
